version: '2.2'
services:
  node:
    build: .devcontainer
    working_dir: /opt/remote-development-firebase
    ports:
      - "5000:5000"
      - "9005:9005"
    volumes:
      - ./:/opt/remote-development-firebase
      - functions_node_modules:/opt/remote-development-firebase/src/functions/node_modules
    command: tail -f /dev/null

volumes:
  functions_node_modules:
    driver: 'local'
